- name: Create the glance database
  shell: mysql -e "CREATE DATABASE glance;"

# TODO update glance password here
- name: Grant proper access to the glance database
  shell: |
    mysql -e "CREATE USER 'glance'@'localhost' IDENTIFIED BY 'password';"
    mysql -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost';"
    mysql -e "CREATE USER 'glance'@'%' IDENTIFIED BY 'password';"
    mysql -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%';"
#   https://ma.ttias.be/mysql-8-removes-shorthand-creating-user-permissions/

# TODO update glance password here
- name: Create the glance user
  shell: openstack user create --domain default --password password glance

- name: Add the admin role to the glance user and service project
  shell: openstack role add --project service --user glance admin

- name: Create the glance service entity
  shell: openstack service create --name glance --description "OpenStack Image" image

- name: Create the Image service API endpoints
  shell: |
    openstack endpoint create --region RegionOne image public http://controller:9292
    openstack endpoint create --region RegionOne image internal http://controller:9292
    openstack endpoint create --region RegionOne image admin http://controller:9292

- name:  install glance
  apt:
    name: glance
    state: latest

# TODO update glance password here
- name: Edit the /etc/glance/glance-api.conf file
  ini_file:
    path: /etc/glance/glance-api.conf
    owner: glance
    group: glance
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { section: "database", option: "connection", value: 'mysql+pymysql://glance:password@localhost/glance' }
    - { section: "keystone_authtoken", option: "www_authenticate_uri", value: 'http://controller:5000' }
    - { section: "keystone_authtoken", option: "auth_url", value: 'http://controller:5000' }
    - { section: "keystone_authtoken", option: "memcached_servers", value: 'controller:11211' }
    - { section: "keystone_authtoken", option: "auth_type", value: 'password' }
    - { section: "keystone_authtoken", option: "project_domain_name", value: 'Default' }
    - { section: "keystone_authtoken", option: "user_domain_name", value: 'Default' }
    - { section: "keystone_authtoken", option: "project_name", value: 'service' }
    - { section: "keystone_authtoken", option: "username", value: 'glance' }
    - { section: "keystone_authtoken", option: "password", value: 'password' }
    - { section: "paste_deploy", option: "flavor", value: 'keystone' }
    - { section: "glance_store", option: "stores", value: 'file,http' }
    - { section: "glance_store", option: "default_store", value: 'file' }
    - { section: "glance_store", option: "filesystem_store_datadir", value: '/var/lib/glance/images/' }

- name: Populate the Image service database
  shell: su -s /bin/sh -c "glance-manage db_sync" glance

- name: Restart service glance-api
  service:
    name: glance-api
    state: restarted

- name: add cirros image
  shell: |
    wget http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
    glance image-create --name "cirros" \
      --file cirros-0.4.0-x86_64-disk.img \
      --disk-format qcow2 --container-format bare \
      --visibility=public