- name:  install the packages
  apt:
    name: neutron-linuxbridge-agent
    state: latest

- name: Edit the /etc/neutron/neutron.conf file
  ini_file:
    path: /etc/neutron/neutron.conf
    owner: neutron
    group: neutron
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { section: "DEFAULT", option: "transport_url", value: 'rabbit://openstack:password@controller' }
    - { section: "DEFAULT", option: "auth_strategy", value: "keystone" }
    - { section: "keystone_authtoken", option: "www_authenticate_uri", value: 'http://controller:5000' }
    - { section: "keystone_authtoken", option: "auth_url", value: 'http://controller:5000' }
    - { section: "keystone_authtoken", option: "memcached_servers", value: 'controller:11211' }
    - { section: "keystone_authtoken", option: "auth_type", value: 'password' }
    - { section: "keystone_authtoken", option: "project_domain_name", value: 'Default' }
    - { section: "keystone_authtoken", option: "user_domain_name", value: 'Default' }
    - { section: "keystone_authtoken", option: "project_name", value: 'service' }
    - { section: "keystone_authtoken", option: "username", value: 'neutron' }
    - { section: "keystone_authtoken", option: "password", value: 'password' }
    - { section: "oslo_concurrency", option: "lock_path", value: '/var/lib/neutron/tmp' }

- name: Edit the /etc/neutron/plugins/ml2/linuxbridge_agent.ini file
  ini_file:
    path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: neutron
    group: neutron
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { section: "linux_bridge", option: "physical_interface_mappings", value: "provider:{{ ansible_facts['default_ipv4']['interface'] }}" }
    - { section: "vxlan", option: "enable_vxlan", value: true }
    - { section: "vxlan", option: "local_ip", value: "{{ ipreg.stdout_lines[0] }}" }
    - { section: "vxlan", option: "l2_population", value: true }
    - { section: "securitygroup", option: "enable_security_group", value: true }
    - { section: "securitygroup", option: "firewall_driver", value: "neutron.agent.linux.iptables_firewall.IptablesFirewallDriver" }


- name: Edit the /etc/nova/nova.conf file
  ini_file:
    path: /etc/nova/nova.conf
    owner: nova
    group: nova
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { section: "neutron", option: "auth_url", value: 'http://controller:5000' }
    - { section: "neutron", option: "auth_type", value: 'password' }
    - { section: "neutron", option: "project_domain_name", value: 'default' }
    - { section: "neutron", option: "user_domain_name", value: 'default' }
    - { section: "neutron", option: "region_name", value: 'RegionOne' }
    - { section: "neutron", option: "project_name", value: 'service' }
    - { section: "neutron", option: "username", value: 'neutron' }
    - { section: "neutron", option: "password", value: 'password' }

- name: Restart the Networking services & nova-compute
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - nova-compute
    - neutron-linuxbridge-agent