- name:  install the packages
  apt:
    name: [neutron-server, neutron-plugin-ml2, neutron-linuxbridge-agent, neutron-l3-agent, neutron-dhcp-agent, neutron-metadata-agent]
    state: latest

- name: Edit the /etc/neutron/neutron.conf file
  copy:
    src: controller-neutron.conf
    dest: /etc/neutron/neutron.conf
    owner: neutron
    group: neutron
    mode: u=rw,g=rw,o=r

- name: Edit the /etc/neutron/plugins/ml2/ml2_conf.ini file
  copy:
    src: ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: neutron
    group: neutron
    mode: u=rw,g=rw,o=r

- name: Edit the /etc/neutron/plugins/ml2/linuxbridge_agent.ini file
  template:
    src: linuxbridge_agent.ini
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: neutron
    group: neutron
    mode: u=rw,g=rw,o=r

- name: Edit the /etc/neutron/l3_agent.ini file
  copy:
    src: l3_agent.ini
    dest: /etc/neutron/l3_agent.ini
    owner: neutron
    group: neutron
    mode: u=rw,g=rw,o=r

- name: Edit the /etc/neutron/dhcp_agent.ini file
  copy:
    src: dhcp_agent.ini
    dest: /etc/neutron/dhcp_agent.ini
    owner: neutron
    group: neutron
    mode: u=rw,g=rw,o=r