- name: Create the nova_api, nova, and nova_cell0 databases
  shell: |
    mysql -e "CREATE DATABASE nova_api;"
    mysql -e "CREATE DATABASE nova;"
    mysql -e "CREATE DATABASE nova_cell0;"

- name: Grant proper access to the databases
  shell: |
    mysql -e "CREATE USER 'nova'@'localhost' IDENTIFIED BY 'password';"
    mysql -e "GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'localhost';"
    mysql -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost';"
    mysql -e "GRANT ALL PRIVILEGES ON nova_cell0.* TO 'nova'@'localhost';"
    mysql -e "CREATE USER 'nova'@'%' IDENTIFIED BY 'password';"
    mysql -e "GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'%';"
    mysql -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%';"
    mysql -e "GRANT ALL PRIVILEGES ON nova_cell0.* TO 'nova'@'%';"
#   https://ma.ttias.be/mysql-8-removes-shorthand-creating-user-permissions/

- name: Create the Compute service credentials
  shell: openstack user create --domain default --password password nova

- name: Add the admin role to the nova user
  shell: openstack role add --project service --user nova admin

- name: Create the nova service entity
  shell: openstack service create --name nova --description "OpenStack Compute" compute

- name: Create the Compute API service endpoints
  shell: |
    openstack endpoint create --region RegionOne compute public http://controller:8774/v2.1
    openstack endpoint create --region RegionOne compute internal http://controller:8774/v2.1
    openstack endpoint create --region RegionOne compute admin http://controller:8774/v2.1

- name: Install the packages
  apt:
    name: [nova-api, nova-conductor, nova-novncproxy, nova-scheduler]
    state: latest

- name: Edit the /etc/nova/nova.conf file
  template:
    src: controller-nova.conf
    dest: /etc/nova/nova.conf
    owner: nova
    group: nova
    mode: u=rw,g=rw,o=r

- name: Populate the nova-api database
  shell: su -s /bin/sh -c "nova-manage api_db sync" nova

- name: Register the cell0 database
  shell: su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova

- name: Create the cell1 cell
  shell: su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova

- name: Populate the nova database
  shell: su -s /bin/sh -c "nova-manage db sync" nova

- name: Verify nova cell0 and cell1 are registered correctly
  shell: su -s /bin/sh -c "nova-manage cell_v2 list_cells" nova

- name: Restart the Compute services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy