- name: Install the packages
  apt:
    name: etcd
    state: latest

- name: Edit the /etc/default/etcd file
  template:
    src: etcd
    dest: /etc/default/etcd
    owner: root
    group: root
    mode: u=rw,g=rw,o=r

- name: Enable and restart the etcd service
  systemd:
    name: etcd
    state: restarted
    enabled: True