- name: install chrony
  include: chrony.yml

- name: configure dns server
  include: dns.yml

- name:  install MariaDB
  when: "'controller' in {{ group_names }}"
  include: mysql.yml

- name: install openstack client
  include: os-client.yml

- name: install kubectl
  include: kubectl.yml

- name: install terraform
  include: terraform.yml

- name: install rabbitmq
  include: rabbitmq.yml
  when: "'controller' in {{ group_names }}"

- name: install memcached
  include: memcached.yml
  when: "'controller' in {{ group_names }}"

- name: install cockpit
  apt:
    name: cockpit
    state: latest

- name: start cockpit
  systemd:
    name: cockpit
    state: started
    enabled: true

- name: install etcd
  include: etcd.yml
  when: "'controller' in {{ group_names }}"