- name: install chrony
  include: chrony.yml

- name:  install MariaDB
  when: "'controller' in {{ group_names }}"
  apt:
    name: mysql-server
    state: latest

- name: install openstack client
  include: os-client.yml