- name: Enable Repo OpenStack wallaby for Ubuntu 20.04 LTS
  shell: add-apt-repository -y cloud-archive:wallaby

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install the OpenStack client
  apt:
    name: python3-openstackclient
    state: latest

- name: Install pip
  shell: |
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python3 get-pip.py

- name: install virtualenv, ansible and openstacksdk
  shell: pip3 install virtualenv openstacksdk ansible

- name: add ips to hosts file
  shell: |
    echo "{{ controller_ip }}  controller" >> /etc/hosts
    echo "{{ compute1_ip }}  compute1" >> /etc/hosts