- name: Install and configure controller node
  include: controller-install.yml
  when: "'controller' in {{ group_names }}"

- name: Install and configure a storage node
  include: storage-install.yml
  when: "'storage' in {{ group_names }}"

- name:  Install nfs client
  apt:
    name: nfs-common
    state: latest

- name: Verify Cinder operation
  shell: openstack volume service list
  register: cindereg

- name: print previous command output
  debug:
    var: cindereg.stdout_lines