- name:  Install the supporting utility packages
  apt:
    name: nfs-kernel-server
    state: latest

- name: Exporting a General Purpose Mount
  sell: |
    mkdir /var/nfs/general -p
    sudo chown nobody:nogroup /var/nfs/general

- name: Configuring the NFS Exports
  shell: echo "/var/nfs/general    {{ subnet }}(rw,sync,no_subtree_check)" >> /etc/exports

- name: Configure the share
  shell: |
    echo "{{ hostvars[inventory_hostname]['groups']['storage'][0] }}:/var/nfs/general" > /etc/cinder/nfs_share
    chown root:cinder /etc/cinder/nfs_share
    chmod 0640 /etc/cinder/nfs_share

- name:  Install the packages
  apt:
    name: cinder-volume
    state: latest
    
- name: Edit the /etc/cinder/cinder.conf file
  ini_file:
    path: /etc/cinder/cinder.conf
    owner: cinder
    group: cinder
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { section: "database", option: "connection", value: 'mysql+pymysql://cinder:password@controller/cinder' }
    - { section: "DEFAULT", option: "transport_url", value: 'rabbit://openstack:password@controller' }
    - { section: "DEFAULT", option: "my_ip", value: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}" }
    - { section: "DEFAULT", option: "auth_strategy", value: "keystone" }
    - { section: "DEFAULT", option: "enabled_backends", value: "nfs" }
    - { section: "DEFAULT", option: "glance_api_servers", value: "http://controller:9292" }
    - { section: "keystone_authtoken", option: "www_authenticate_uri", value: 'http://controller:5000' }
    - { section: "keystone_authtoken", option: "auth_url", value: 'http://controller:5000' }
    - { section: "keystone_authtoken", option: "memcached_servers", value: 'controller:11211' }
    - { section: "keystone_authtoken", option: "auth_type", value: 'password' }
    - { section: "keystone_authtoken", option: "project_domain_name", value: 'Default' }
    - { section: "keystone_authtoken", option: "user_domain_name", value: 'Default' }
    - { section: "keystone_authtoken", option: "project_name", value: 'service' }
    - { section: "keystone_authtoken", option: "username", value: 'cinder' }
    - { section: "keystone_authtoken", option: "password", value: 'password' }
    - { section: "nfs", option: "nfs_shares_config", value: '/etc/cinder/nfs_share' }
    - { section: "nfs", option: "volume_driver", value: 'cinder.volume.drivers.nfs.NfsDriver' }
    - { section: "nfs", option: "volume_backend_name", value: 'nfsbackend' }
    - { section: "oslo_concurrency", option: "lock_path", value: '/var/lib/cinder/tmp' }


- name: Restart the Block Storage volume service including its dependencies
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - nfs-kernel-server
    - cinder-volume