- name: Create the barbican database
  shell: mysql -e "CREATE DATABASE barbican;"

# TODO update barbican password here
- name: Grant proper access to the barbican database
  shell: |
    mysql -e "CREATE USER 'barbican'@'localhost' IDENTIFIED BY 'password';"
    mysql -e "GRANT ALL PRIVILEGES ON barbican.* TO 'barbican'@'localhost';"
    mysql -e "CREATE USER 'barbican'@'%' IDENTIFIED BY 'password';"
    mysql -e "GRANT ALL PRIVILEGES ON barbican.* TO 'barbican'@'%';"
#   https://ma.ttias.be/mysql-8-removes-shorthand-creating-user-permissions/

# TODO update barbican password here
- name: Create the barbican user
  shell: openstack user create --domain default --password password barbican

- name: Add the admin role to the barbican user and service project
  shell: openstack role add --project service --user barbican admin

- name: Create the creator role
  shell: openstack role create creator

- name: Add the creator role to the barbican user
  shell: openstack role add --project service --user barbican creator

- name: Create the barbican service entity
  shell: openstack service create --name barbican --description "Key Manager" key-manager

- name: Create the Container Infrastructure Management service API endpoints
  shell: |
    openstack endpoint create --region RegionOne key-manager public http://controller:9311
    openstack endpoint create --region RegionOne key-manager internal http://controller:9311
    openstack endpoint create --region RegionOne key-manager admin http://controller:9311

- name: Install the common and library packages
  apt:
    name: [barbican-api, barbican-keystone-listener, barbican-worker]
    state: latest

- name: Edit the /etc/barbican/barbican.conf file
  ini_file:
    path: /etc/barbican/barbican.conf
    owner: barbican
    group: barbican
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { section: "DEFAULT", option: "transport_url", value: 'rabbit://openstack:password@localhost' }
    - { section: "DEFAULT", option: "sql_connection", value: "mysql+pymysql://barbican:password@localhost/barbican" }
    - { section: "keystone_authtoken", option: "www_authenticate_uri", value: 'http://controller:5000' }
    - { section: "keystone_authtoken", option: "auth_url", value: 'http://controller:5000' }
    - { section: "keystone_authtoken", option: "memcached_servers", value: 'controller:11211' }
    - { section: "keystone_authtoken", option: "auth_type", value: 'password' }
    - { section: "keystone_authtoken", option: "project_domain_name", value: 'Default' }
    - { section: "keystone_authtoken", option: "user_domain_name", value: 'Default' }
    - { section: "keystone_authtoken", option: "project_name", value: 'service' }
    - { section: "keystone_authtoken", option: "username", value: 'barbican' }
    - { section: "keystone_authtoken", option: "password", value: 'password' }

- name: Populate the Key Manager service database
  shell: su -s /bin/sh -c "barbican-manage db upgrade" barbican

- name: Restart the Key Manager services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - barbican-keystone-listener
    - barbican-worker
    - apache2