- hosts: all
  gather_facts: no
  become: yes
  roles:
    - openstack

- hosts: controller
  gather_facts: no
  become: yes
  roles:
    - keystone
    - glance
    - placement
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: password
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: http://controller:5000/v3
    OS_IDENTITY_API_VERSION: 3